export const TODOADDREQUEST = "TODOADDREQUEST"
export const TODOADDSUCCESS = "TODOADDSUCCESS"
export const TODOADDFAILURE = "TODOADDFAILURE"



export const ADDTODO = "ADDTODO"
export const UPDATETODO = "UPDATETODO"
export const REMOVETODO = "REMOVETODO"


export const COMPLETETODO = "COMPLETETODO"
export const PENDINGTODO = "COMPLETETODO"
