export const TODOADDREQUEST = "TODOADDREQUEST"
export const TODOADDSUCCESS = "TODOADDSUCCESS"
export const TODOADDFAILURE = "TODOADDFAILURE"



export const ADDTODO = "ADDTODO"
export const REMOVETODO = "REMOVETODO"
